In [3]:
import numpy as np

In [11]:
np.array([1,2.,3.], dtype=int)

array([1, 2, 3])

In [13]:
meuPequenoArray = np.arange(1,11)
meuPequenoArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
meuPequenoArray = meuPequenoArray * meuPequenoArray

meuPequenoArray

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
import pandas as pd

In [24]:
d = {'Campeão': 'Flamengo', 'Vice':'Vasco', 'Terceiro':'Bangu'}
pd.Series ([5, 6, 8, -3, 9])

s2 = pd.Series(d)

s2

Campeão     Flamengo
Terceiro       Bangu
Vice           Vasco
dtype: object

In [25]:
dados = np.random.random(4)
indices = np.arange(0, 8, 2)
s3 = pd.Series(data = dados, index = indices)

In [26]:
s3

0    0.597503
2    0.799374
4    0.084988
6    0.313782
dtype: float64

In [53]:
# dados
# dados da tabela usando dicionario 
tabelaDicionario = {
    "sexo":         ["F","M","F","F","M","M","F","F","F","M","F"],
    "predileta":    ["H","M","P","H","C","H","M","P","H","C","P"],
    "nota":         [5,8,8,6,5,6,8,4,2,6,8]
}

dados = pd.DataFrame(tabelaDicionario)

dados.get("nota")

0     5
1     8
2     8
3     6
4     5
5     6
6     8
7     4
8     2
9     6
10    8
Name: nota, dtype: int64

In [62]:
d = {'Times Paulistas': ['São Paulo', 'Santos', 'Corinthians'], 
     'Times Cariocas': ['Flamengo', 'Fluminense', 'Botafogo'], 
     'Times Ruins': ['Palmeiras', 'Vasco', 'Remo']}
df = pd.DataFrame(d)

df['Times Cariocas']

0      Flamengo
1    Fluminense
2      Botafogo
Name: Times Cariocas, dtype: object

In [63]:
d = {'Times Paulistas': ['São Paulo', 'Santos', 'Corinthians'], 
     'Times Cariocas': ['Flamengo', 'Fluminense', 'Botafogo'], 
     'Times Ruins': ['Palmeiras', 'Vasco', 'Remo']}
df = pd.DataFrame(d, index=['1º', '2º', '3º'])

df[['Times Paulistas','Times Ruins']]

Times Paulistas Times Ruins
1º       São Paulo   Palmeiras
2º          Santos       Vasco
3º     Corinthians        Remo

In [65]:
listas = [[9,3,6], [6,9], [6,1,6]]
df3 = pd.DataFrame(listas, (2,3,4),['A', 'B', 'C'])
df3

A  B    C
2  9  3  6.0
3  6  9  NaN
4  6  1  6.0

In [69]:
df3.replace(np.nan, 10)

A  B     C
2  9  3   6.0
3  6  9  10.0
4  6  1   6.0

In [88]:
dados = pd.read_csv('c:/Users/IFPB/Desktop/kaggle/train.csv')

dados[['name','sex']]

name     sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
5                                     Moran, Mr. James    male
6                              McCarthy, Mr. Timothy J    male
7                       Palsson, Master. Gosta Leonard    male
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9                  Nasser, Mrs. Nicholas (Adele Achem)  female
10                     Sandstrom, Miss. Marguerite Rut  female
11                            Bonnell, Miss. Elizabeth  female
12                      Saundercock, Mr. William Henry    male
13                         Andersson, Mr. Anders Johan    male
14                Vestrom, Miss. Hulda Amanda Adolfina  female
15                    Hewlett, Mrs. (Mary D Kingcome)   female
16                                Rice, Master. Eugene    male
17                        Williams, Mr. Charles Eugene    male
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19                             Masselmani, Mrs. Fatima  female
20                                Fynney, Mr. Joseph J    male
21                               Beesley, Mr. Lawrence    male
22                         McGowan, Miss. Anna "Annie"  female
23                        Sloper, Mr. William Thompson    male
24                       Palsson, Miss. Torborg Danira  female
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female
26                             Emir, Mr. Farred Chehab    male
27                      Fortune, Mr. Charles Alexander    male
28                       O'Dwyer, Miss. Ellen "Nellie"  female
29                                 Todoroff, Mr. Lalio    male
..                                                 ...     ...
861                        Giles, Mr. Frederick Edward    male
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female
863                  Sage, Miss. Dorothy Edith "Dolly"  female
864                             Gill, Mr. John William    male
865                           Bystrom, Mrs. (Karolina)  female
866                       Duran y More, Miss. Asuncion  female
867               Roebling, Mr. Washington Augustus II    male
868                        van Melkebeke, Mr. Philemon    male
869                    Johnson, Master. Harold Theodor    male
870                                  Balkic, Mr. Cerin    male
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female
872                           Carlsson, Mr. Frans Olof    male
873                        Vander Cruyssen, Mr. Victor    male
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female
875                   Najib, Miss. Adele Kiamie "Jane"  female
876                      Gustafsson, Mr. Alfred Ossian    male
877                               Petroff, Mr. Nedelio    male
878                                 Laleff, Mr. Kristo    male
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
880       Shelley, Mrs. William (Imanita Parrish Hall)  female
881                                 Markun, Mr. Johann    male
882                       Dahlberg, Miss. Gerda Ulrika  female
883                      Banfield, Mr. Frederick James    male
884                             Sutehall, Mr. Henry Jr    male
885               Rice, Mrs. William (Margaret Norton)  female
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]